version: "2.3"

services:
  web:
    build: "web"
    env_file: "env"
    init: true
    restart: always
    ports:
      - "8080:80"
    volumes_from:
      - "fpm:ro"
  fpm:
    build: "app"
    env_file: "env"
    init: true
    restart: always
    volumes:
      - "./volumes/www:/var/www/html"
      - "./volumes/data:/var/www/html/data"
  database:
    image: postgres:15.1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
    env_file: "env"
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
